#!/usr/bin/env bash
set -euo pipefail

# Multi-Swarm LiteLLM Gateway Setup
# Reads tokens from ~/.claude/multi-swarm/tokens.json
# Generates litellm config with multi-model routing and starts the gateway
# Supports three model tiers: opus, sonnet, haiku

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source model-router.sh for tier constants (TIER_OPUS, TIER_SONNET, TIER_HAIKU)
# shellcheck source=model-router.sh
source "$SCRIPT_DIR/model-router.sh"

TOKENS_FILE="$HOME/.claude/multi-swarm/tokens.json"
CONFIG_DIR="$HOME/.claude/multi-swarm"
LITELLM_CONFIG="$CONFIG_DIR/litellm-config.yaml"
GATEWAY_PID_FILE="$CONFIG_DIR/gateway.pid"
GLOBAL_CONFIG="$CONFIG_DIR/config.json"

# Read gateway config
PORT=$(jq -r '.gateway.port // 4000' "$GLOBAL_CONFIG" 2>/dev/null || echo "4000")
MASTER_KEY=$(jq -r '.gateway.masterKey // "sk-swarm-master"' "$GLOBAL_CONFIG" 2>/dev/null || echo "sk-swarm-master")
ROUTING=$(jq -r '.gateway.routingStrategy // "usage-based-routing-v2"' "$GLOBAL_CONFIG" 2>/dev/null || echo "usage-based-routing-v2")
COOLDOWN=$(jq -r '.gateway.cooldownSeconds // 60' "$GLOBAL_CONFIG" 2>/dev/null || echo "60")
ALLOWED_FAILS=$(jq -r '.gateway.allowedFails // 2' "$GLOBAL_CONFIG" 2>/dev/null || echo "2")

# Check if gateway is already running
if [ -f "$GATEWAY_PID_FILE" ]; then
    OLD_PID=$(cat "$GATEWAY_PID_FILE")
    if kill -0 "$OLD_PID" 2>/dev/null; then
        echo "Gateway already running on PID $OLD_PID"
        # Verify it's healthy
        if curl -sf -H "Authorization: Bearer ${MASTER_KEY}" "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then
            echo "Gateway healthy on port $PORT"
            exit 0
        else
            echo "Gateway process exists but unhealthy, restarting..."
            kill "$OLD_PID" 2>/dev/null || true
            sleep 2
        fi
    fi
fi

# Check for tokens
if [ ! -f "$TOKENS_FILE" ]; then
    echo "ERROR: No tokens file found at $TOKENS_FILE"
    echo "Create it with: echo '[\"token1\", \"token2\", ...]' > $TOKENS_FILE && chmod 600 $TOKENS_FILE"
    exit 1
fi

TOKEN_COUNT=$(jq 'length' "$TOKENS_FILE")
echo "Found $TOKEN_COUNT tokens in $TOKENS_FILE"

if [ "$TOKEN_COUNT" -eq 0 ]; then
    echo "ERROR: No tokens found in $TOKENS_FILE"
    exit 1
fi

# Generate LiteLLM config from template or inline
echo "Generating LiteLLM config..."

# All three model tiers to configure in the gateway
MODEL_TIERS=("$TIER_OPUS" "$TIER_SONNET" "$TIER_HAIKU")

cat > "$LITELLM_CONFIG" << YAML_HEADER
# Auto-generated by multi-swarm gateway-setup.sh
# Do not edit manually — regenerated on each gateway start

general_settings:
  master_key: ${MASTER_KEY}
  enable_jwt_auth: false

router_settings:
  routing_strategy: ${ROUTING}
  cooldown_time: ${COOLDOWN}
  num_retries: 3
  allowed_fails: ${ALLOWED_FAILS}
  retry_after: 5
  enable_pre_call_checks: true
  model_group_alias:
    opus: "${TIER_OPUS}"
    sonnet: "${TIER_SONNET}"
    haiku: "${TIER_HAIKU}"

model_list:
YAML_HEADER

# Add token deployments for each model tier
# Every token gets an entry under every model tier (all tokens can access all models)
INDEX=0
for MODEL in "${MODEL_TIERS[@]}"; do
    jq -r '.[]' "$TOKENS_FILE" | while read -r TOKEN; do
        cat >> "$LITELLM_CONFIG" << EOF
  - model_name: ${MODEL}
    litellm_params:
      model: anthropic/${MODEL}
      api_key: ${TOKEN}
    model_info:
      id: "${MODEL}-token-${INDEX}"
EOF
        INDEX=$((INDEX + 1))
    done
done

TOTAL_DEPLOYMENTS=$(( TOKEN_COUNT * ${#MODEL_TIERS[@]} ))
echo "Generated config with ${#MODEL_TIERS[@]} model tiers x $TOKEN_COUNT tokens = $TOTAL_DEPLOYMENTS deployments"

# Start LiteLLM
echo "Starting LiteLLM gateway on port $PORT..."
nohup litellm --config "$LITELLM_CONFIG" --port "$PORT" \
    > "$CONFIG_DIR/gateway.log" 2>&1 &
echo $! > "$GATEWAY_PID_FILE"

echo "Gateway PID: $(cat "$GATEWAY_PID_FILE")"

# Wait for health
echo "Waiting for gateway to be healthy..."
for i in $(seq 1 30); do
    if curl -sf -H "Authorization: Bearer ${MASTER_KEY}" "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then
        echo "Gateway healthy on port $PORT after ${i}s"
        exit 0
    fi
    sleep 1
done

echo "ERROR: Gateway failed to start within 30s"
echo "Check logs: cat $CONFIG_DIR/gateway.log"
exit 1
